### ISSUE TITLE
issue with ui 

### ISSUE THREAD

**Issue by ylp1455** [sajitha00/recipiapp#12]
its hard to see the caption in the create post page 

![WhatsApp Image 2024-04-11 at 00 26 00_3802d0fe](https://github.com/sajitha00/recipiapp/assets/115799462/481718c2-ccb5-4f8b-b2db-4629f6acdbb8)

**Comment by ylp1455** [comment]
@sajitha00

**Comment by sajitha00** [comment]
Fixed @ylp1455
